console.log("hello")
console.log("new line added to the js file")
console.log("i may delete this  later")
console.log("new change1 ")
console.log("bad code")
console.log("bad code 2")
console.log("to be reverted")